modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3"
issueTrackerURL="https://github.com/Nosiphus/nosiphus-furniture-mod/issues"

[[mods]]
modId="nfm"
version="2023.09.14"
displayName="Nosiphus Furniture Mod"
updateJSONURL=""
displayURL="https://www.nosiphus.com/"
logoFile="nfm.png"
credits="MrCrayFish, Ocelot"
authors="Nosiphus"
description="Nosiphus Furniture Mod is an addon to MrCrayFish's Furniture Mod that readds old furniture."

[[dependencies.nfm]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.10,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nfm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nfm]]
    modId="cfm"
    mandatory=true
    versionRange="[7.0.0-pre34,)"
    ordering="AFTER"
    side="BOTH"

[modproperties.nfm]
    catalogueItemIcon="nfm:white_modern_chair"
    configuredBackground="minecraft:textures/block/white_concrete.png"